# Generated by Django 4.2.4 on 2023-08-29 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='today_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
